version: '1'
services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=adminpassword
    depends_on:
      - mongo

  app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - mongo
    environment:
      - DB_URL=mongo
      - PORT=3000

volumes:
  mongo-data: